[cursor.style]
blinking = "On"
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 12
[font.normal]
family = "PlemolJP Console NF"
style = "Regular"

[window]
blur = true
opacity = 0.7
option_as_alt = "Both"

[window.padding]
x = 8
y = 8
